# Generated by Django 4.0.4 on 2022-05-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='section_pics')),
                ('period', models.CharField(choices=[('Incas', 'Incas'), ('Colonial', 'Colonial'), ('Independencia', 'Independencia'), ('Presente', 'Presente')], max_length=64)),
                ('category', models.CharField(choices=[('Historia', 'Historia'), ('Geografía', 'Geografía'), ('Costumbres', 'Costumbres')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=1024)),
                ('order', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='section_pics')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page')),
            ],
        ),
    ]
