# Generated by Django 4.0.4 on 2022-05-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_page_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('Historia', 'Historia'), ('Geografía', 'Geografía'), ('Costumbres', 'Costumbres')], max_length=64),
        ),
        migrations.AlterField(
            model_name='page',
            name='period',
            field=models.CharField(choices=[('Incas', 'Incas'), ('Colonial', 'Colonial'), ('Monarquía del Perú', 'Monarquía del Perú'), ('Independencia', 'Independencia'), ('Presente', 'Presente')], max_length=64),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(max_length=8192),
        ),
    ]
