# Generated by Django 4.0.4 on 2022-06-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('Historia', 'Historia'), ('Costumbres', 'Costumbres'), ('Places', 'Places')], max_length=64),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=8192)),
                ('image', models.ImageField(upload_to='place_pics')),
                ('likes', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='core.page')),
            ],
        ),
    ]
