# Generated by Django 4.0.4 on 2022-06-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_page_title_alter_page_category_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
